[package]
name = "iron-wilds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_prototype_lyon = "0.9.0"
rand = "0.8.5"
bevy-inspector-egui = "0.19.0"


[target.'cfg(unix)'.dependencies]
bevy = { version="0.11.3", features=["wayland"]}
