on:
  pull_request:
  push:
    branches:
      - main


name: Lint, Test, Build

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev
          sudo apt-get install -y lld libxcursor-dev alsa libegl1-mesa libegl1
          rustup update
          rustup component add clippy
          rustup install nightly

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          cargo build --release
