on:
  pull_request:
  push:
    branches:
      - main


name: cargo fmt

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: |
          cargo fmt --all --check