on:
  pull_request:
  push:
    branches:
      - main


name: Lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev
          sudo apt-get install -y lld libxcursor-dev alsa libegl1-mesa libegl1
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy